gpu_num: 0

batch_size: 8
num_classes: 11172
input_size: 64

sample_img_path: '/root/paper_project/Data/Hangul_Characters_Image64_Grayscale/8f42217bf172a009.png'
style_path: 'weight/style_enc.pth'
model_path: 'weight/torch_quantization.pt'

sampling_chars: "하늘을우러러한점버그없기를자그만디버깅에도나는괴로워했다"