gpu_num: 1

batch_size: 8
num_classes: 11172
input_size: 64

sample_img_path: '../Data/Hangul_Characters_Image64_Grayscale/나눔손글씨강인한위로_쓜.png'
style_path: 'weight/style_enc.pth'
model_path: '/home/hojun/Documents/code/cr_diffusion/KD-Font/ML/results/models/self_attention445_1_2/ckpt_370.pt'

sampling_chars: "쓜졎꿥밙껪챣릗뱅욨떰"